<?php
namespace Amin\CPL_CoreGuard\Core;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use Amin\CPL_CoreGuard\Utils\Utils;

/**
 * Pure Logic: This class "thinks" but never "touches" the disk.
 */
class Config_Generator {

	public const WP_CONFIG_MARKER = '/* CPL CoreGuard v1 */';

	/**
	 * Build the string for the MU-Plugin config file.
	 */
	public function get_config_file_contents(): string {
		$name    = get_option( 'cpl_site_name', get_bloginfo( 'name' ) );
		$color   = Utils::sanitize_hex_color( get_option( 'cpl_brand_color', '#38bdf8' ) );
		$message = sanitize_textarea_field( get_option( 'cpl_maint_msg', 'Technical update in progress.' ) );
		$locale  = preg_replace( '/[^a-zA-Z_-]/', '', get_locale() );
		$icon    = esc_url_raw( get_option( 'cpl_site_icon_url', '' ) );

		$php  = "<?php\n";
		$php .= "/** Generated by CPL CoreGuard — do not edit manually. */\n";
		$php .= "defined( 'ABSPATH' ) || exit;\n\n";
		$php .= "defined( 'CPL_SITE_NAME' )     || define( 'CPL_SITE_NAME',     '" . addslashes( $name ) . "' );\n";
		$php .= "defined( 'CPL_BRAND_COLOR' )    || define( 'CPL_BRAND_COLOR',    '" . addslashes( $color ) . "' );\n";
		$php .= "defined( 'CPL_MAINT_MSG' )      || define( 'CPL_MAINT_MSG',      '" . addslashes( $message ) . "' );\n";
		$php .= "defined( 'CPL_LOCALE' )         || define( 'CPL_LOCALE',         '" . addslashes( $locale ) . "' );\n";
		$php .= "defined( 'CPL_SITE_ICON_URL' )  || define( 'CPL_SITE_ICON_URL', '" . addslashes( $icon ) . "' );\n";

		return $php;
	}

	/**
	 * Build the string for the db-error.php drop-in.
	 */
	public function get_db_error_dropin_contents(): string {
		$mu_path_esc = addslashes( trailingslashit( WPMU_PLUGIN_DIR ) . CPL_COREGUARD_MU_FILE );

		$code  = "<?php\n";
		$code .= "if ( file_exists( '{$mu_path_esc}' ) ) {\n";
		$code .= "    require_once '{$mu_path_esc}';\n";
		$code .= "    if ( function_exists( 'cpl_render_ui' ) ) {\n";
		$code .= "        cpl_render_ui();\n";
		$code .= "    }\n";
		$code .= "}\n";

		return $code;
	}

	/**
	 * Logic for modifying wp-config content.
	 */
	public function get_wp_config_modified_content( string $current_content ): ?string {
		if ( str_contains( $current_content, self::WP_CONFIG_MARKER ) ) {
			return null; // No change needed
		}

		$snippet  = "\n" . self::WP_CONFIG_MARKER . "\n";
		$snippet .= "if ( ! defined( 'WP_CLI' ) || ! WP_CLI ) {\n";
		$snippet .= "    if ( is_readable( __DIR__ . '/wp-content/mu-plugins/" . CPL_COREGUARD_MU_FILE . "' ) ) {\n";
		$snippet .= "        require_once __DIR__ . '/wp-content/mu-plugins/" . CPL_COREGUARD_MU_FILE . "';\n";
		$snippet .= "    }\n";
		$snippet .= "}\n";

		return preg_replace( '/^(<\?php\s)/i', '$1' . $snippet, $current_content, 1 );
	}
}
