name: Run Tests
on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Matches your plugin requirements
          extensions: mbstring, xml, ctype, iconv

      - name: Install Dependencies
        run: composer install --no-progress --ignore-platform-reqs

      - name: Run PHPUnit
        run: vendor/bin/phpunit

      # - name: Run PHPCS
      #   run: vendor/bin/phpcs